"""Tests for the LANGUAGE_MAP in config.py.

Verifies that every BCP-47 code from the frontend SUPPORTED_LANGUAGES list
is covered — either passed through as a Gemini-supported code or mapped to
the closest supported equivalent.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from config import LANGUAGE_MAP  # noqa: E402

# These are the Cloud-Translation-supported codes (NMT + TLLM) that Gemini
# Live API can accept. Keep this in sync if Google's support list changes.
SUPPORTED_BY_GEMINI = {
    "ab",
    "ace",
    "ach",
    "af",
    "ak",
    "alz",
    "am",
    "ar",
    "as",
    "awa",
    "ay",
    "az",
    "ba",
    "ban",
    "bbc",
    "be",
    "bem",
    "bew",
    "bg",
    "bho",
    "bik",
    "bm",
    "bn",
    "br",
    "bs",
    "bts",
    "btx",
    "bua",
    "ca",
    "ceb",
    "cgg",
    "chm",
    "ckb",
    "cnh",
    "co",
    "crh",
    "crs",
    "cs",
    "cv",
    "cy",
    "da",
    "de",
    "din",
    "doi",
    "dov",
    "dv",
    "dz",
    "ee",
    "el",
    "en",
    "eo",
    "es",
    "et",
    "eu",
    "fa",
    "ff",
    "fi",
    "fil",
    "fj",
    "fr",
    "fr-CA",
    "fy",
    "ga",
    "gaa",
    "gd",
    "gl",
    "gn",
    "gom",
    "gu",
    "ha",
    "haw",
    "he",
    "hi",
    "hil",
    "hmn",
    "hr",
    "hrx",
    "ht",
    "hu",
    "hy",
    "id",
    "ig",
    "ilo",
    "is",
    "it",
    "iw",
    "ja",
    "jam",
    "jv",
    "jw",
    "ka",
    "kg",
    "kk",
    "km",
    "kn",
    "ko",
    "kri",
    "ktu",
    "ku",
    "ky",
    "la",
    "lb",
    "lg",
    "li",
    "lij",
    "lmo",
    "ln",
    "lo",
    "lt",
    "ltg",
    "luo",
    "lus",
    "lv",
    "mai",
    "mak",
    "mg",
    "mi",
    "min",
    "mk",
    "ml",
    "mn",
    "mr",
    "ms",
    "ms-Arab",
    "mt",
    "my",
    "mni-Mtei",
    "ne",
    "new",
    "nl",
    "nl-BE",
    "no",
    "nr",
    "nso",
    "nus",
    "ny",
    "oc",
    "om",
    "or",
    "pa",
    "pa-Arab",
    "pag",
    "pam",
    "pap",
    "pl",
    "ps",
    "pt-BR",
    "pt-PT",
    "qu",
    "rn",
    "ro",
    "rom",
    "ru",
    "rw",
    "sa",
    "scn",
    "sd",
    "sg",
    "shn",
    "si",
    "sk",
    "sl",
    "sm",
    "sn",
    "so",
    "sq",
    "sr",
    "ss",
    "st",
    "su",
    "sv",
    "sw",
    "szl",
    "ta",
    "te",
    "tet",
    "tg",
    "th",
    "ti",
    "tk",
    "tl",
    "tn",
    "tr",
    "ts",
    "tt",
    "ug",
    "uk",
    "ur",
    "uz",
    "ve",
    "vi",
    "wo",
    "xh",
    "yi",
    "yo",
    "yua",
    "yue",
    "zh-CN",
    "zh-TW",
    "zu",
}

# All BCP-47 codes from the frontend's SUPPORTED_LANGUAGES list.
ALL_FRONTEND_CODES = [
    "ab",
    "ace",
    "ach",
    "aa",
    "af",
    "sq",
    "alu",
    "am",
    "ar",
    "hy",
    "as",
    "av",
    "awa",
    "ay",
    "az",
    "ban",
    "bal",
    "bm",
    "bci",
    "ba",
    "eu",
    "btx",
    "bts",
    "bbc",
    "be",
    "bem",
    "bn",
    "bew",
    "bho",
    "bik",
    "bs",
    "br",
    "bg",
    "bua",
    "yue",
    "ca",
    "ceb",
    "ch",
    "ce",
    "ny",
    "zh-CN",
    "zh-TW",
    "chk",
    "cv",
    "crh",
    "crh-Latn",
    "hr",
    "cs",
    "da",
    "prs",
    "dv",
    "din",
    "doi",
    "dov",
    "nl",
    "nl-BE",
    "dyu",
    "dz",
    "en",
    "eo",
    "et",
    "ee",
    "fo",
    "fj",
    "fil",
    "fi",
    "fon",
    "fr",
    "fr-CA",
    "fy",
    "fur",
    "ff",
    "gaa",
    "gl",
    "ka",
    "de",
    "el",
    "gn",
    "gu",
    "ht",
    "cnh",
    "ha",
    "haw",
    "he",
    "hil",
    "hi",
    "hmn",
    "hu",
    "hrx",
    "iba",
    "is",
    "ig",
    "ilo",
    "id",
    "iu-Latn",
    "iu",
    "ga",
    "it",
    "jam",
    "ja",
    "jv",
    "kac",
    "kl",
    "kn",
    "kr",
    "pam",
    "kk",
    "kha",
    "km",
    "cgg",
    "kg",
    "rw",
    "kgo",
    "ktu",
    "kv",
    "kok",
    "ko",
    "kri",
    "kmr",
    "ckb",
    "ky",
    "lo",
    "ltg",
    "la",
    "lv",
    "lij",
    "li",
    "ln",
    "lt",
    "lmo",
    "lg",
    "luo",
    "lb",
    "mk",
    "mad",
    "mai",
    "mak",
    "mg",
    "ms",
    "ms-Arab",
    "ml",
    "mt",
    "mam",
    "gv",
    "mi",
    "mr",
    "mh",
    "mwr",
    "mfe",
    "mhr",
    "mni",
    "min",
    "lus",
    "mn",
    "my",
    "nhe",
    "ndc",
    "nr",
    "new",
    "ne",
    "nqo",
    "no",
    "nus",
    "oc",
    "or",
    "om",
    "os",
    "pag",
    "pap",
    "ps",
    "fa",
    "pl",
    "pt-BR",
    "pt-PT",
    "pa-Guru",
    "pa-Arab",
    "qu",
    "kek",
    "rom",
    "ro",
    "rn",
    "ru",
    "se",
    "sm",
    "sg",
    "sa",
    "sat-Latn",
    "sat",
    "gd",
    "nso",
    "sr",
    "st",
    "crs",
    "shn",
    "sn",
    "scn",
    "szl",
    "sd",
    "si",
    "sk",
    "sl",
    "so",
    "es",
    "su",
    "sus",
    "sw",
    "ss",
    "sv",
    "ty",
    "tg",
    "tzm",
    "tzm-Tfng",
    "ta",
    "tt",
    "te",
    "tet",
    "th",
    "bo",
    "ti",
    "tiv",
    "tpi",
    "to",
    "lu",
    "ts",
    "tn",
    "tcy",
    "tum",
    "tr",
    "tk",
    "tyv",
    "tw",
    "udm",
    "uk",
    "ur",
    "ug",
    "uz",
    "ve",
    "vec",
    "vi",
    "war",
    "cy",
    "wo",
    "xh",
    "sah",
    "yi",
    "yo",
    "yua",
    "zap",
    "zu",
]


def test_all_frontend_codes_covered():
    """Every frontend language code either passes through or has a mapping
    that produces a Gemini-supported code."""
    for code in ALL_FRONTEND_CODES:
        mapped = LANGUAGE_MAP.get(code, code)
        assert (
            mapped in SUPPORTED_BY_GEMINI
        ), f"{code!r} (mapped to {mapped!r}) is not in the set of supported Gemini codes"


def test_regional_script_variants_map():
    """Regional script variants that are not directly supported map to base."""
    assert LANGUAGE_MAP["pa-Guru"] == "pa"

    # These are already supported pass-through codes — not in LANGUAGE_MAP.
    assert "zh-CN" not in LANGUAGE_MAP
    assert "pt-BR" not in LANGUAGE_MAP
    assert "fr-CA" not in LANGUAGE_MAP


def test_minority_languages_map_reasonably():
    """Minority languages map to geo-politically or linguistically close majors."""
    assert LANGUAGE_MAP["bo"] == "zh-CN"  # Tibet → Chinese
    assert LANGUAGE_MAP["kl"] == "da"  # Greenlandic → Danish
    assert LANGUAGE_MAP["to"] == "sm"  # Tongan → Samoan
    assert LANGUAGE_MAP["tpi"] == "en"  # Tok Pisin → English
    assert LANGUAGE_MAP["vec"] == "it"  # Venetian → Italian
    assert LANGUAGE_MAP["fur"] == "it"  # Friulian → Italian
    assert LANGUAGE_MAP["war"] == "fil"  # Waray → Filipino


def test_alur_uses_cloud_code():
    """Alur uses the Cloud Translation code `alz`."""
    assert LANGUAGE_MAP["alu"] == "alz"


def test_kituba_maps_to_ktu():
    """Kituba maps to Cloud Translation's `ktu` code."""
    assert LANGUAGE_MAP["kgo"] == "ktu"


def test_same_script_variants():
    """Same-language script variants map to the base supported code."""
    assert LANGUAGE_MAP["crh-Latn"] == "crh"
    assert LANGUAGE_MAP["sat-Latn"] == "bn"
    assert LANGUAGE_MAP["sat"] == "bn"


def test_normalise_helper():
    """Verify the _normalise_lang helper in router."""
    from router import _normalise_lang  # noqa: E402

    # Unsupported code gets mapped
    assert _normalise_lang("bo") == "zh-CN"
    assert _normalise_lang("tpi") == "en"
    # Already-supported code passes through
    assert _normalise_lang("en") == "en"
    assert _normalise_lang("es") == "es"
    assert _normalise_lang("zh-CN") == "zh-CN"


def test_no_identity_mappings():
    """LANGUAGE_MAP should not contain entries that map to themselves."""
    for src, dst in LANGUAGE_MAP.items():
        assert src != dst, f"Identity mapping for {src!r} is useless; remove it"
